name: "Bug report"
description: "Let us know about an unexpected error, a crash, or an incorrect behavior."
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        # Thank you for opening an issue.

        The [OpenTofu Language Server](https://github.com/opentofu/opentofu-ls) issue tracker is reserved for bug reports relating to the OpenTofu Language Server repository.
        We use GitHub issues for tracking bugs and enhancements.
        For questions, please use [the community slack](https://opentofucommunity.slack.com/archives/C08Q08C6H88) where there are more people ready to help.

        ## Filing a bug report

        To fix problems, we need clear reproduction cases - we need to be able to see it happen locally. A reproduction case is ideally something any engineer can git-clone or copy-paste and run immediately, without inventing any details or context.

        * A short example can be directly copy-pasteable; longer examples should be in separate git repositories, especially if multiple files are needed
        * Please include all needed context. For example, if you figured out that an expression can cause a crash, put the expression in a variable definition or a resource
        * Set defaults on (or omit) any variables. The person reproducing it should not need to invent variable settings
        * Omit any unneeded complexity: remove variables, conditional statements, functions, etc. that are not needed to trigger the bug

  - type: textarea
    id: community-note
    attributes:
      label: Community note
      description: Please leave this note unchanged.
      value: |
        > [!TIP]
        > 👋 Hi there, OpenTofu community! The OpenTofu team prioritizes issues based on upvotes. Please make sure to upvote this issue and describe how it affects you in detail in the comments to show your support.

  - type: input
    id: ls-version
    attributes:
      label: Language Server Version
      description: |
        Run `tofu-ls --version` to show the version.
        If you are not running the latest version, please try upgrading because your issue may have already been fixed.
      placeholder: v0.31.2
    validations:
      required: true

  - type: input
    id: tofu-version
    attributes:
      label: OpenTofu Version
      description: |
        Run `tofu -v` to show the version. Make sure you are running the same binary that the language server would normally pick up from $PATH if you have more than one version installed on your system.
      placeholder: OpenTofu v1.9.0 on linux_amd64
    validations:
      required: true

  - type: input
    id: client
    attributes:
      label: Client Version
      description: |
        Please share what IDE and/or plugin interacts with the server.
      placeholder: Sublime Text (LSP plugin) v0.9.7
    validations:
      required: true

  - type: textarea
    id: configuration
    attributes:
      label: OpenTofu Configuration
      description: |
        Include the relevant OpenTofu configuration that might be helpful for reproducing your issue.
        Please remove any sensitive information such as passwords before sharing configuration snippets.

        For OpenTofu configs larger than a few resources, please consider using another GitHub repository or a GitHub gist.
      placeholder: |
        resource "aws_instance" "web" {
          ami           = "ami-a1b2c3d4"
          instance_type = "t2.micro"
        }

        # etc...
      render: terraform
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: |
        Please list the steps required to reproduce the issue. If applicable, add screenshots to help explain your problem.
      placeholder: |
        1. Open a folder in IDE XYZ
        2. Open file example.tf from that folder
        3. Trigger autocompletion on line 5, column 1 (1-indexed)
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: |
        What should have happened? Please give a clear and concise description in plain English.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: |
        What actually happened? Please give a clear and concise description in plain English.
    validations:
      required: true

  - type: input
    id: gist
    attributes:
      label: Gist
      description: |
        If possible, please provide a link to a [GitHub Gist](https://gist.github.com/) with your full debug output.
        Do *NOT* pastethe debug output in the issue, since it may be long.

        Full debug output can be obtained by launching the server with a particular flag (e.g. `-log-file`).
        Please follow the instructions in [`docs/TROUBLESHOOTING.md`](https://github.com/opentofu/opentofu-ls/blob/main/docs/TROUBLESHOOTING.md).

        Debug output may contain sensitive information. Please review it before posting publicly.
      placeholder: |
        https://gist.github.com/gdb/b6365e79be6052e7531e7ba6ea8caf23
    validations:
      required: false

  - type: textarea
    id: workarounds
    attributes:
      label: Workarounds
      description: |
        Did you discover any workarounds on your own? If so, please list them here.
    validations:
      required: false

  - type: textarea
    id: references
    attributes:
      label: References
      description: |
        Are there any other GitHub issues (open or closed) or pull requests that relate to this issue? Or links to documentation pages?
        Guide to referencing Github issues: https://help.github.com/articles/basic-writing-and-formatting-syntax/#referencing-issues-and-pull-requests
      placeholder: |
        - #123
        - #456
        - opentofu/opentofu#123
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Help Wanted
      description: Is this something you're able to or interested in helping out with? This is not required but a helpful way to signal to us that you're planning to open a PR with a fix.
      options:
        - label: I'm interested in contributing a fix myself
          required: false
