name: "Documentation issue or request"
description: "Report if something is incorrect in our docs, or suggest additions and improvements to our documentation"
labels: [documentation]
body:
  - type: markdown
    attributes:
      value: |
        # Thank you for opening a feature request.

        The [OpenTofu Language Server](https://github.com/opentofu/opentofu-ls) issue tracker is reserved for bug reports relating to the OpenTofu Language Server repository.
        We use GitHub issues for tracking bugs and enhancements.
        For questions, please use [the community slack](https://opentofucommunity.slack.com/archives/C08Q08C6H88) where there are more people ready to help.
  - type: textarea
    id: community-note
    attributes:
      label: Community note
      description: Please leave this note unchanged.
      value: |
        > [!TIP]
        > 👋 Hi there, OpenTofu community! The OpenTofu team prioritizes issues based on upvotes. Please make sure to upvote (👍) this issue and describe how it affects you in detail in the comments to show your support.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the issue in plain English.
    validations:
      required: true

  - type: textarea
    id: links
    attributes:
      label: Links
      description: |
        Include links to affected or related documentation page(s) or issues.
        Guide to referencing Github issues: https://help.github.com/articles/basic-writing-and-formatting-syntax/#referencing-issues-and-pull-requests
      placeholder: |
        - https://github.com/opentofu/opentofu-ls/blob/main/docs/TROUBLESHOOTING.md
        - #123
        - #456
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Help Wanted
      description: Is this something you're able to or interested in helping out with? This is not required but a helpful way to signal to us that you're planning to open a PR with a fix.
      options:
        - label: I'm interested in contributing a fix myself
          required: false
